# Functions

In [1]:
# Defining a function
def my_function():
  print('Hello')

In [3]:
#Calling the function
my_function()

Hello


In [6]:
# Single arguments
def my_function(a):
    print('Northeastern University, '+str(a))

In [7]:
my_function('Boston')


Northeastern University, Boston


In [8]:
# Multiple arguments
def my_function(a,b):
    print(str(a)+ ' ' +str(b))
   

In [10]:
my_function('Northeastern', 'University')

Northeastern University


In [11]:
# Multiple arguments as positional argument
def my_function(a,b):
    print(str(a)+ ' ' +str(b))

In [12]:
my_function('Northeastern', 'University')

Northeastern University


In [13]:
# Multiple arguments as keyword argument
my_function(b='University', a='Northeastern')

Northeastern University


In [14]:
# Default arguments
def my_function(a,b="Univeristy"):
    print(str(a)+ ' ' +str(b))

In [15]:
my_function('Northeastern')

Northeastern Univeristy


In [16]:
my_function('Northeastern', 'Boston')

Northeastern Boston


In [18]:
# Default arguments
def my_function(b,a="University"):
    print(str(a)+ ' ' +str(b))

In [19]:
# Optional arguments
def my_function(a,b):
    print(str(a))

In [21]:
# return a single value
def add(a,b):
    y=a+b
    return y

In [22]:
add(1,2)

3

# Return other data types


In [24]:
# Return a list
def vector(a,b):
    y=list(range(a,(b+1)))
    return y

In [25]:
z=vector(1,10)
print(z)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [26]:
# Return a dictionary
def dictionary(a,b):
    y={'University':a,'City':b}
    return y

In [27]:
z=dictionary('NEU','Boston')
print(z)

{'City': 'Boston', 'University': 'NEU'}


# Classes

In [28]:
# Class
#A function inside a class is called a method
class op():
    def add(self,a,b):
        y=a+b
        return y

    def sub(self,a,b):
        y=a-b
        return y


print(op().add(1,2))
print(op().sub(1,2))




3
-1


In [29]:
#creating an object of the class
obj=op()

print(obj.add(1,2))
print(obj.sub(1,2))

3
-1


# Modules

In [30]:
# Module
#Create a file called calc.py (text file with .py extension) 
import calc as cl
dir(cl) # get a list of functions inside the module
cl.funcname()


ImportError: No module named calc

# Numpy

In [6]:
# Numpy- numerical python
import numpy as np
a = np.array([1, 2, 3])
print(type(a))
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(type(b))
print(b)

<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [7]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [12]:
a = np.zeros((1,2))
print(a)
print(a.shape)

[[ 0.  0.]]
(1, 2)


In [42]:
b = np.ones((1,2)) 
print(b)

c = np.ones((1,2), dtype=np.int16) 
print(c)


[[ 1.  1.]]
[[1 1]]


In [44]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [20]:
e = np.random.random((2,2))
print(e)

[[ 0.28711038  0.44920005]
 [ 0.69672281  0.85881495]]


In [22]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [30]:
# Access individual elements
a[0,1]

2

In [31]:
# Change individual elements
a[0,1]=100
print(a)

[[  1 100   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [37]:
# Select rows and cols
print(a[1,:])
print(a[:,1])
print(a[1:3,:])

[5 6 7 8]
[100   6  10]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
# Slicing/subsetting arrays
b = a[1:3, 1:3]
print(b)

[[ 6  7]
 [10 11]]


In [38]:
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
a+b

array([5, 7, 9])

In [41]:
a = np.ones((1,2)) 
b= np.ones((1,2)) 
a+b

array([[ 2.,  2.]])

In [46]:
a=np.array([1, 2, 3])
np.mean(a)

2.0

In [47]:
np.sum(a)

6

In [48]:
np.min(a)

1

In [49]:
np.max(a)

3

# Pandas

In [31]:
import pandas as pd
data=pd.read_csv('test.csv')
data

Name  Age  Weight
0    a   10      50
1    b   15      60
2    c   30      70
3    d   50      65

In [56]:
#Get the number of rows and columns
data.shape

(4, 3)

In [67]:
# Select first 'n' rows and columns
data.head(2)

Name  Age  Weight
0    a   10      50
1    b   15      60

In [68]:
#Select last 'n' rows and column
data.tail(2)

Name  Age  Weight
2    c   30      70
3    d   50      65

In [69]:
data.sample(frac=0.5)

Name  Age  Weight
2    c   30      70
1    b   15      60

In [70]:
#Indexed location in dataframe
data.sample(n=2)

Name  Age  Weight
1    b   15      60
0    a   10      50

In [72]:
data.iloc[1:3]

Name  Age  Weight
1    b   15      60
2    c   30      70

In [75]:
data.nlargest(2, 'Age')

Name  Age  Weight
3    d   50      65
2    c   30      70

In [76]:
data.nsmallest(2, 'Age')

Name  Age  Weight
0    a   10      50
1    b   15      60

In [92]:
data[['Age']]

Age
0   10
1   15
2   30
3   50

In [88]:
data[['Name','Age']]

Name  Age
0    a   10
1    b   15
2    c   30
3    d   50

In [107]:
data.loc[:,'Name':'Weight']

Name  Age  Weight
0    a   10      50
1    b   15      60
2    c   30      70
3    d   50      65

In [99]:
data.loc[1:3,'Name':'Weight']

Name  Age  Weight
1    b   15      60
2    c   30      70
3    d   50      65

In [32]:
data.iloc[:,1:2]

Age
0   10
1   15
2   30
3   50

In [103]:
data.iloc[1:3,1:2]

Age
1   15
2   30

In [108]:
data.loc[data['Age']>15]

Name  Age  Weight
2    c   30      70
3    d   50      65

In [109]:
data.loc[data['Age']>15,['Name','Weight']]

Name  Weight
2    c      70
3    d      65

In [110]:
data['Age'].value_counts()

15    1
30    1
10    1
50    1
Name: Age, dtype: int64

In [111]:
len(data)

4

In [113]:
data['Age'].nunique()

4

In [114]:
data.describe()

Age     Weight
count   4.000000   4.000000
mean   26.250000  61.250000
std    17.969882   8.539126
min    10.000000  50.000000
25%    13.750000  57.500000
50%    22.500000  62.500000
75%    35.000000  66.250000
max    50.000000  70.000000

In [115]:
data.sum()

Name      abcd
Age        105
Weight     245
dtype: object

In [116]:
data['Age'].sum()

105

In [117]:
data['Age'].min()

10

In [118]:
data['Age'].mean()

26.25

In [135]:
data['Height']=data['Weight']*1.2
data

Name  Age  Weight  Height
0    a   10      50    60.0
1    b   15      60    72.0
2    c   30      70    84.0
3    d   50      65    78.0

In [125]:
data.dtypes

Name       object
Age         int64
Weight      int64
Height    float64
dtype: object

In [126]:
data['Age'].dtypes

dtype('int64')

In [138]:
temp=['e', 60,70,200.0]
data.loc[4]=temp
data

Name  Age  Weight  Height
0    a   10      50    60.0
1    b   15      60    72.0
2    c   30      70    84.0
3    d   50      65    78.0
4    e   60      70   200.0